---
version: "3"

vars:
  PHP_CMD: compose exec php
  SF_CMD: "{{.PHP_CMD}} bin/console"
  PWA_CMD: "compose exec pwa"

tasks:
  build:
    cmds:
      - task: build:php
      - task: build:pwa
  
  build:php:
    cmds:
      - docker compose build php
  
  build:pwa:
    cmds:
      - docker compose build pwa
  
  build:prod:
    cmds:
      - docker compose -f compose.yaml -f compose.prod.yaml build
  boot:
    cmds:
      - docker compose up -d
  
  stop:
    cmds:
      - docker compose stop
  
  php:shell:
    cmds:
      - docker {{.PHP_CMD}} bash
  
  php:test:
    cmds:
      - task: php:stan
      - task: php:unit

  php:unit:
    cmds:
      - docker {{.PHP_CMD}} bin/phpunit

  php:stan:
    cmds:
      - docker {{.PHP_CMD}} ./vendor/bin/phpstan

  sf:
    cmds:
      - docker {{.SF_CMD}} {{.CLI_ARGS}}
  
  composer:
    cmds:
      - docker {{.PHP_CMD}} composer {{.CLI_ARGS}}
  
  pnpm:
    cmds:
      - docker {{.PWA_CMD}} pnpm {{.CLI_ARGS}}
