api_platform:
  path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
  title: Purus API Specification
  version: 1.0.0
  formats:
    json: ['application/json']
    jsonld: ['application/ld+json']
  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
  mercure:
    include_type: true

  oauth:
    enabled: true
    clientId: '%env(OIDC_SWAGGER_CLIENT_ID)%'
    pkce: true
    type: oauth2
    flow: authorizationCode
    tokenUrl: '%env(OIDC_SERVER_URL)%/token/'
    authorizationUrl: '%env(OIDC_SERVER_URL)%/authorize/'
    scopes:
      openid: (required) Indicates that the application intends to use OIDC to verify the user's identity
      email: (required)
      profile: (required)
