---
name: Build Container Images

on:
  workflow_call:

# Do not use concurrency to prevent simultaneous helm deployments
jobs:
  build:
    name: Build Container Images
    runs-on: ubuntu-latest
    env:
      PHP_DOCKER_IMAGE: ghcr.io/kilip/purus-php:${{ github.sha }}
      PWA_DOCKER_IMAGE: ghcr.io/kilip/purus-pwa:${{ github.sha }}
    permissions:
      packages: "write"
      contents: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          # push and load may not be set together
          # must push manually in a next step
          pull: true
          load: true
          files: |
            compose.yaml
            compose.prod.yaml
          set: |
            *.cache-from=type=gha,scope=${{ github.ref }}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{ github.ref }},mode=max

      - name: Docker push
        run: |
          docker push $PHP_DOCKER_IMAGE
          docker push $PWA_DOCKER_IMAGE

      - name: Docker tag and push latest
        if: github.event_name != 'pull_request'
        run: |
          docker tag $PHP_DOCKER_IMAGE ghcr.io/kilip/purus-php:${{ github.ref_name }}
          docker tag $PWA_DOCKER_IMAGE ghcr.io/kilip/purus-pwa:${{ github.ref_name }}

          docker tag $PHP_DOCKER_IMAGE ghcr.io/kilip/purus-php:latest
          docker tag $PWA_DOCKER_IMAGE ghcr.io/kilip/purus-pwa:latest

          docker push ghcr.io/kilip/purus-php:${{ github.ref_name }}
          docker push ghcr.io/kilip/purus-pwa:${{ github.ref_name }}
          docker push ghcr.io/kilip/purus-php:latest
          docker push ghcr.io/kilip/purus-pwa:latest
