---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    uses: kilip/purus/.github/workflows/check.yaml@main
    secrets: inherit

  api-test:
    name: API Testing
    needs: ["check"]
    if: ${{ needs.check.result != 'failure' }}
    uses: kilip/purus/.github/workflows/api.yaml@main
    secrets: inherit

  build-images:
    name: Build
    needs: ["check", "api-test"]
    if: ${{ needs.check.result != 'failure' && github.ref_name == 'main'}}
    uses: 'kilip/purus/.github/workflows/build-images.yaml@main'
    secrets: inherit
    permissions:
      contents: write
      packages: write
